FROM debian:12-slim

ARG IMAGE_VERSION="v1.0.0-devel"
ARG MAINTAINER="https://github.com/jsknnr/soulmask-dedicated-server"

ARG CONTAINER_GID=10000
ARG CONTAINER_UID=10000

ENV DEBIAN_FRONTEND="noninteractive"
ENV SOULMASK_PATH="/home/steam/soulmask"
ENV STEAMCMD_PATH="/home/steam/steamcmd"
ENV STEAM_SDK64_PATH="/home/steam/.steam/sdk64"
ENV STEAM_APP_ID="3017300"

ENV GAME_PORT="27050"
ENV QUERY_PORT="27051"
ENV SERVER_SLOTS="50"
ENV LISTEN_ADDRESS="0.0.0.0"
ENV SERVER_LEVEL="Level01_Main"
ENV GAME_MODE="pve"
ENV BACKUP=900
ENV SAVING=600

RUN groupadd -g ${CONTAINER_GID} steam \
    && useradd -g ${CONTAINER_GID} -u ${CONTAINER_UID} -m steam \
    && dpkg --add-architecture i386 \
    && apt-get update \
    && apt-get install -y \
        ca-certificates \
        curl \
        lib32gcc-s1 \
        locales \
        procps \
    && echo 'LANG="en_US.UTF-8"' > /etc/default/locale \
    && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
    && locale-gen \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean \
    && apt-get autoremove -y

USER steam

COPY entrypoint.sh /home/steam/entrypoint.sh

RUN mkdir -p ${SOULMASK_PATH} \
    && mkdir -p ${STEAMCMD_PATH} \
    && curl -sqL https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz | tar zxvf - -C ${STEAMCMD_PATH} \
    && chmod +x ${STEAMCMD_PATH}/steamcmd.sh \
    && ${STEAMCMD_PATH}/steamcmd.sh +quit \
    && mkdir -p ${STEAM_SDK64_PATH} \
    && cp ${STEAMCMD_PATH}/linux64/steamclient.so ${STEAM_SDK64_PATH}/steamclient.so \
    && echo "${IMAGE_VERSION}" > /home/steam/image_version \
    && echo "${MAINTAINER}" > /home/steam/image_maintainer \
    && echo "${CONTAINER_UID}:${CONTAINER_GID}" > /home/steam/expected_filesystem_permissions
 
WORKDIR /home/steam

CMD ["/home/steam/entrypoint.sh"]
